### ISSUE TITLE
Add a LICENSE?

### ISSUE THREAD

**Issue by isikyus** [joakin/elm-canvas-sketch#1]
Reading https://github.com/joakin/elm-canvas#usage, I see this repository is intended as a project template. However, it doesn't include any explicit license. Per GitHub terms of service I believe this means I can fork it, but not really use the code outside of that GH fork.

If the intent is for people to `git clone` elm-canvas-sketch and build their project from that starting point, could you make it explicit that this is allowed?

**Comment by joakin** [comment]
My bad, I forgot elm applications had no license field in the elm.json.

I've added the MIT license on the repo https://github.com/joakin/elm-canvas-sketch/commit/475c701db88fb9f076c45bd7ee865c2549b79e4c
